### ISSUE TITLE
Resolution of package.json and default package.json

### ISSUE THREAD

**Issue by Undistraction** [elboman/gatsby-remark-embedded-codesandbox#1]
Would be great if the plugin used a simple resolution algorithm to resolve the `package.json` for the example.  It should look in the example's directory, then in the root code directory, then fall-back to the simplest possible config (as outlined in the README): 

```
{
  "name": "example",
  "dependencies": {}
}
```

This would:

- make sure the plugin worked out of the box
- allow a single shared `package.json` to be shared amongst multiple examples

**Comment by elboman** [comment]
Yeah, I totally see what you mean, if you use the plugin for small examples (i.e in blog posts), it becomes tedious to have a `package.json` for every example.

> then in the root code directory

Not sure if you mean the root examples folder as set in the plugin config, or the project root folder. Cause I'd say it go up until the root examples folder and stop there (and use the default fall-back as proposed).

I'll keep you post!

**Comment by Undistraction** [comment]
Yes. I meant to the root examples dir.

So ideally you could do:

Examples
   - react 
     - alpha
     - bravo

And either have a `package.json` in 'alpha' dir, one in 'react' dir or one in the root 'examples' dir.
