### ISSUE TITLE
v2?

### ISSUE THREAD

**Issue by alisonjoseph** [elboman/gatsby-remark-embedded-codesandbox#4]
Does this work with v2 of Gatsby? Doesn't seem to, but not sure if I was doing something wrong. 😸 

`Error: Unable to find plugin "gastby-remark-embedded-codesandbox". Perhaps you need to install its package?`

**Comment by alisonjoseph** [comment]
nvm 😉

**Comment by fredvisser** [comment]
To be clear, the issue was a typo in the gatsby-config.js example in the README. 
Should be:
```resolve: 'gatsby-remark-embedded-codesandbox',``` 
not:
```resolve: 'gastby-remark-embedded-codesandbox',```
